"""Initial migration

Revision ID: 4f33fa9db4a6
Revises: 
Create Date: 2025-01-14 18:12:01.337963

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f33fa9db4a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=20), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('subcategory',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('warranty_card',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('image', sa.String(length=200), nullable=True),
                    sa.Column('product_name', sa.String(length=100), nullable=False),
                    sa.Column('warranty_number', sa.String(length=80), nullable=False),
                    sa.Column('product_purchase_date', sa.Date(), nullable=False),
                    sa.Column('warranty_expiry_date', sa.Date(), nullable=False),
                    sa.Column('warranty_provider', sa.String(length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('subcategory_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('warranty_number')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_card')
    op.drop_table('subcategory')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
