"""Add image column to Warranty table

Revision ID: 9bc81c0e5762
Revises: 
Create Date: 2025-01-07 21:06:26.510668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc81c0e5762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warranty_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warranty_card', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
